# Generated by Django 5.0.2 on 2024-11-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=40, null=True),
        ),
    ]
