# Generated by Django 5.0.2 on 2024-11-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_remove_creditcard_card_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(choices=[('biweekly', 'Every 2 Weeks'), ('monthly', 'Monthly')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
